### ISSUE TITLE
Using query and size together

### ISSUE THREAD

**Issue by schowdhury** [matthuhiggins/arelastic#24]
I would expect something like this to work, but Query does not take any options (such as size).  

```
Arelastic::Searches::Query.new(
      Arelastic::Builders::Queries.match('some_key', 'some_value'), size: 100
    )
```
to generate something like:

```
{query: {match: {some_key: 'some_value'}}, size: 100}
```

But, it does not.  What am I missing?

**Comment by malept** [comment]
[`size`](https://www.elastic.co/guide/en/elasticsearch/reference/7.2/search-request-from-size.html) is outside of the query, so you'd use a `Arelastic::Nodes::HashGroup`. To use your example:

```ruby
Arelastic::Nodes::HashGroup.new([
  Arelastic::Searches::Query.new(Arelastic::Builders::Queries.match('some_key', 'some_value')),
  Arelastic::Searches::Size.new(100)
])
```
Which produces (when calling `#as_elastic`):
```ruby
{"query"=>{"match"=>{"some_key"=>"some_value"}}, "size"=>100}
```
